site_name: "Documentació de Pràctiques"
theme:
  name: material
nav:
  - Inici: index.md
  - Pràctiques:
      - Exercici 1: Practicas/Exercici1/Exercici1.md
      - Exercici 2: Practicas/Exercici2/Exercici2.md
      - Exercici 3: Practicas/Exercici3/Exercici3.md
